# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('saltname', models.CharField(max_length=32, verbose_name='salt minion name')),
            ],
            options={
                'db_table': 'code_update_minions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目组')),
            ],
            options={
                'db_table': 'code_update_servergroup',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=128, verbose_name='项目名字')),
                ('env', models.IntegerField(blank=True, choices=[(1, '生产环境'), (2, '测试环境')], null=True, verbose_name='运行环境')),
                ('owner', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=256)),
                ('ports', models.CharField(max_length=128, null=True, verbose_name='ports')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_update.ServiceGroup')),
                ('saltminion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_update.Minion')),
            ],
            options={
                'db_table': 'code_update_servicesname',
                'ordering': ['id'],
            },
        ),
    ]
