# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField(db_index=True, verbose_name='zabbix hostid')),
                ('host', models.CharField(max_length=50, null=True, verbose_name='zabbix hostname')),
                ('ip', models.CharField(db_index=True, max_length=32, verbose_name='zabbix ip')),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Server')),
            ],
            options={
                'db_table': 'zabbix_cache_host',
                'ordering': ['id'],
            },
        ),
    ]
