# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='机房名称首字母')),
                ('idc_name', models.CharField(default='', max_length=100, verbose_name='机房名称')),
                ('address', models.CharField(default='', max_length=255, verbose_name='机房地址')),
                ('phone', models.CharField(default='', max_length=25, verbose_name='机房联系电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='机房联系邮件')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='联系人')),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.IntegerField(null=True, verbose_name='产商')),
                ('manufacturers', models.CharField(max_length=50, null=True)),
                ('manufacture_date', models.DateField(null=True)),
                ('server_type', models.CharField(max_length=20, null=True)),
                ('sn', models.CharField(db_index=True, max_length=60, null=True)),
                ('os', models.CharField(max_length=50, null=True)),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True)),
                ('inner_ip', models.CharField(max_length=32, null=True, unique=True)),
                ('mac_address', models.CharField(max_length=50, null=True)),
                ('ip_info', models.CharField(max_length=255, null=True)),
                ('server_cpu', models.CharField(max_length=250, null=True)),
                ('server_disk', models.CharField(max_length=100, null=True)),
                ('server_mem', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(db_index=True, max_length=100, null=True)),
                ('remark', models.TextField(null=True)),
                ('service_id', models.IntegerField(db_index=True, null=True)),
                ('server_purpose', models.IntegerField(db_index=True, null=True)),
                ('check_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('vm_status', models.IntegerField(db_index=True, null=True)),
                ('uuid', models.CharField(db_index=True, max_length=100, null=True)),
                ('idc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Idc')),
            ],
            options={
                'db_table': 'resources_server',
                'ordering': ['id'],
            },
        ),
    ]
